export const NEW_ORDER_REQUEST = 'NEW_ORDER_REQUEST'
export const NEW_ORDER_SUCCESS = 'NEW_ORDER_SUCCESS'
export const NEW_ORDER_FAIL = 'NEW_ORDER_FAIL'

export const SHOW_ORDER_REQUEST = 'SHOW_ORDER_REQUEST'
export const SHOW_ORDER_SUCCESS = 'SHOW_ORDER_SUCCESS'
export const SHOW_ORDER_FAIL = 'SHOW_ORDER_FAIL'

//Admin all orders

export const ALL_ORDER_REQUEST = 'ALL_ORDER_REQUEST'
export const ALL_ORDER_SUCCESS = 'ALL_ORDER_SUCCESS'
export const ALL_ORDER_FAIL = 'ALL_ORDER_FAIL'
//Update orders

export const UPDATE_ORDER_REQUEST = 'UPDATE_ORDER_REQUEST'
export const UPDATE_ORDER_SUCCESS = 'UPDATE_ORDER_SUCCESS'
export const UPDATE_ORDER_FAIL = 'UPDATE_ORDER_FAIL'
export const UPDATE_ORDER_RESET = 'UPDATE_ORDER_FAIL'

//delete orders admin

export const DELETE_ORDER_REQUEST = 'DELETE_ORDER_REQUEST'
export const DELETE_ORDER_SUCCESS = 'DELETE_ORDER_SUCCESS'
export const DELETE_ORDER_FAIL = 'DELETE_ORDER_FAIL'
export const DELETE_ORDER_RESET = 'DELETE_ORDER_FAIL'

export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST'
export const ORDER_DETAIL_SUCCESS = 'ORDER_DETAIL_SUCCESS'
export const ORDER_DETAIL_FAIL = 'ORDER_DETAIL_FAIL'

export const CLEAR_ERROR = 'CLEAR_ERROR';