export const LOGIN_REQUEST ="LOGIN_REQUEST"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"
//Register
export const REGISTER_USER_REQUEST = 'REGISTER_USER_REQUEST'
export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCES'
export const REGISTER_USER_FAIL = 'REGISTER_USER_FAIL'
export const CLEAR_ERROR = "CLEAR_ERROR"
//Load user
export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAIL = 'LOAD_USER_FAIL'
//Update user
export const UPDATE_USER_REQUEST= 'UPDATE_USER_REQUEST'
export const UPDATE_USER_SUCCESS= 'UPDATE_USER_SUCCESS'
export const UPDATE_USER_RESET = 'UPDATE_USER_RESET'
export const UPDATE_USER_FAIL = 'UPDATE_USER_FAIL'
//Update password
export const UPDATE_PASSWORD_REQUEST="UPDATE_PASSWORD_REQUEST"
export const UPDATE_PASSWORD_SUCCESS="UPDATE_PASSWORD_SUCCESS"
export const UPDATE_PASSWORD_RESET = "UPDATE_PASSWORD_RESET"
export const UPDATE_PASSWORD_FAIL="UPDATE_PASSWORD_FAIL"

//Forgot password
export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCES'
export const FORGOT_PASSWORD_FAIL ='FORGOT_PASSWORD_FAIL'

//Reset password
export const NEW_PASSWORD_REQUEST= 'NEW_PASSWORD_REQUEST'
export const NEW_PASSWORD_SUCCESS = 'NEW_PASSWORD_SUCCESS'
export const NEW_PASSWORD_FAIL = 'NEW_PASSWORD_FAIL'

//All users (ADMIN)

export const ALL_USERS_REQUEST= 'ALL_USERS_REQUEST'
export const ALL_USERS_SUCCESS = 'ALL_USERS_SUCCESS'
export const ALL_USERS_FAIL = 'ALL_USERS_FAIL'

//User details (ADMIN)
export const DETAILS_USERS_REQUEST= 'DETAILS_USERS_REQUEST'
export const DETAILS_USERS_SUCCESS = 'DETAILS_USERS_SUCCESS'
export const DETAILS_USERS_FAIL = 'DETAILS_USERS_FAIL'

//Update User (ADMIN)

export const UPDATE_USERS_REQUEST= 'UPDATE_USERS_REQUEST'
export const UPDATE_USERS_SUCCESS = 'UPDATE_USERS_SUCCESS'
export const UPDATE_USERS_FAIL = 'UPDATE_USERS_FAIL'
export const UPDATE_USERS_RESET = 'UPDATE_USERS_RESET'

//DELETE USERS (admin)
export const DELETE_USERS_REQUEST= 'DELETE_USERS_REQUEST'
export const DELETE_USERS_SUCCESS = 'DELETE_USERS_SUCCESS'
export const DELETE_USERS_FAIL = 'DELETE_USERS_FAIL'
export const DELETE_USERS_RESET = 'DELETE_USERS_RESET'


//Logout user
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAIL = 'LOGOUT_FAIL'
